#!/bin/sh
## Add this file to the .git/hooks directory to enable it.
## This will reject a commit if any tests or style checks fail,
## which will hopefully guarantee a fairly smooth Travis build.
## If necessary, you can force a commit using the --no-verify flag.

make all
